version: '3.8'
services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    container_name: app_container
    volumes:
      - type: bind
        source: ./src
        target: /src
  web:
    build:
      dockerfile: ./docker/web/Dockerfile
      context: .
    container_name: nginx_container
    ports:
      - '18000:8000'
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./src
        target: /src
  db:
    build:
      dockerfile: ./docker/db/Dockerfile
      context: .
    container_name: db_container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user 
      MYSQL_USER_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        
volumes:
  mysql-volume:
