version: '3.8'
services:
  web-server-nginx:
    build:
      dockerfile: ./docker/web/dev/Dockerfile
      context: .
    container_name: nginx_container
    ports:
      - '80:80'
    depends_on:
      - web-server-php
    volumes:
      - type: bind
        source: ./src
        target: /app
    networks:
      - my_network
      
  web-server-php:
    build:
      dockerfile: ./docker/app/dev/Dockerfile
      context: .
    container_name: app_container
    ports:
     - "9000:9000"
    volumes:
      - type: bind
        source: ./src
        target: /app
    networks:
      - my_network

  db:
    build:
      dockerfile: ./docker/db/dev/Dockerfile
      context: .
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: memori
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user 
      MYSQL_USER_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
        
volumes:
  mysql-volume: