apiVersion: v1
kind: Service
metadata:
  name: web-server-nginx
spec:
  type: NodePort
  selector:
    app: web-server-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: web-server-php
spec:
  type: ClusterIP
  selector:
    app: web-server-php
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-nginx
  labels:
    app: web-server-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-nginx
  template:
    metadata:
      labels:
        app: web-server-nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/landlixer/nginx
          ports:
          - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-php
  labels:
    app: web-server-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-php
  template:
    metadata:
      labels:
        app: web-server-php
    spec:
      containers:
        - name: php-fpm 
          image: docker.io/landlixer/php
          ports:
          - containerPort: 9000
          